
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;


/*
ASSIGNMENT # 1 COMP 2130
BILL GRAY QUITALIG
100 950 279

 * Using Java, develop an application for a Quiz.

Problem statement:

The application creates a Quiz and displays a Progress Report. Give a suitable name for your application.

The user enters his/her last name and first name at the beginning of the quiz.

The quiz contains five questions about a hobby, popular music or any other individual interest.
Each question should be a multiple-choice question with two options.
Each question should be worth 25 marks.

When the user answers the question correctly, display a congratulatory message along with the score.

If the user responds to a question incorrectly, display an appropriate message.
The user should be presented with each question continually until it is answered correctly.

The application must keep a track of the number of attempts for each question.
For any question, the user can score:
first attempt  25 marks
second attempt  15 marks
any additional attempt  0 marks

When the user ends the quiz, the application must display a well-formatted Progress Report
(on the screen itself), indicating the following:

- Current date and time
- Full Name of the user
- Marks scored in each attempt
- Marks scored for the quiz
- Percentage score (for e.g. 60/100 would be 60%)
- Number of attempts for each question.

 */


/**
 *
 * @author xzeathri16
 */
public class Quitalig_HeroQuiz extends javax.swing.JFrame {

    /**
     * Creates new form Quitalig_HeroQuiz
     */
    
    //First Name and Last Name of the Player
    String fname, lname;
    
    DateFormat dateFormat = new SimpleDateFormat("EEE, d MMM yyyy HH:mm:ss");
    Date date = new Date();

    
    // multi-dimensional array to hold attempts in "[1]" and hold the score in "[2]" for the questions
    int quiz_info [][] = new int [2][4]; 
    
    public Quitalig_HeroQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        bLoginAndPlay = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bIronmanQ1 = new javax.swing.JButton();
        bThorQ1 = new javax.swing.JButton();
        bCaptAmericaQ1 = new javax.swing.JButton();
        bHulkQ1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bIronmanQ2 = new javax.swing.JButton();
        bThorQ2 = new javax.swing.JButton();
        bCaptAmericaQ2 = new javax.swing.JButton();
        bHulkQ2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bIronmanQ3 = new javax.swing.JButton();
        bThorQ3 = new javax.swing.JButton();
        bCaptAmericaQ3 = new javax.swing.JButton();
        bHulkQ3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bIronmanQ4 = new javax.swing.JButton();
        bThorQ4 = new javax.swing.JButton();
        bCaptAmericaQ4 = new javax.swing.JButton();
        bHulkQ4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        timePlayed = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        totalScore = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KNOW YOUR AVENGER  QUIZ by Bill Gray Quitalig");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("First Name :");

        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("Last Name :");

        bLoginAndPlay.setBackground(new java.awt.Color(0, 0, 0));
        bLoginAndPlay.setForeground(new java.awt.Color(255, 255, 255));
        bLoginAndPlay.setText("LOGIN & PLAY");
        bLoginAndPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginAndPlayActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(0, 0, 0));
        bExit.setForeground(new java.awt.Color(255, 255, 255));
        bExit.setText("EXIT");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bLoginAndPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLoginAndPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.add(jLayeredPane1);
        jLayeredPane1.setBounds(100, 148, 320, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p19qv3vi0f1akb1jng3p10nd3vn3.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 470);

        jTabbedPane1.addTab("LOGIN AND PLAY", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        bIronmanQ1.setBackground(new java.awt.Color(0, 0, 0));
        bIronmanQ1.setForeground(new java.awt.Color(255, 255, 255));
        bIronmanQ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironmanicon.jpg"))); // NOI18N
        bIronmanQ1.setText(" IRON MAN");
        bIronmanQ1.setEnabled(false);
        bIronmanQ1.setIconTextGap(35);
        bIronmanQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIronmanQ1ActionPerformed(evt);
            }
        });

        bThorQ1.setBackground(new java.awt.Color(0, 0, 0));
        bThorQ1.setForeground(new java.awt.Color(255, 255, 255));
        bThorQ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thoricon.jpg"))); // NOI18N
        bThorQ1.setText("THOR");
        bThorQ1.setEnabled(false);
        bThorQ1.setIconTextGap(35);
        bThorQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThorQ1ActionPerformed(evt);
            }
        });

        bCaptAmericaQ1.setBackground(new java.awt.Color(0, 0, 0));
        bCaptAmericaQ1.setForeground(new java.awt.Color(255, 255, 255));
        bCaptAmericaQ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captamericaicon.jpg"))); // NOI18N
        bCaptAmericaQ1.setText("CAPTAIN AMERICA");
        bCaptAmericaQ1.setEnabled(false);
        bCaptAmericaQ1.setIconTextGap(10);
        bCaptAmericaQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptAmericaQ1ActionPerformed(evt);
            }
        });

        bHulkQ1.setBackground(new java.awt.Color(0, 0, 0));
        bHulkQ1.setForeground(new java.awt.Color(255, 255, 255));
        bHulkQ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkicon.jpg"))); // NOI18N
        bHulkQ1.setText("HULK");
        bHulkQ1.setEnabled(false);
        bHulkQ1.setIconTextGap(25);
        bHulkQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHulkQ1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("Who was found frozen on the Artic and revived by S.H.I.E.L.D.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 204, 255));
        jLabel5.setText("He is a Super Soldier and a war veteran of World War II.");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avlogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCaptAmericaQ1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(bIronmanQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bThorQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIronmanQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bThorQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCaptAmericaQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("QUESTION # 1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        bIronmanQ2.setBackground(new java.awt.Color(0, 0, 0));
        bIronmanQ2.setForeground(new java.awt.Color(255, 255, 255));
        bIronmanQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironmanicon.jpg"))); // NOI18N
        bIronmanQ2.setText(" IRON MAN");
        bIronmanQ2.setEnabled(false);
        bIronmanQ2.setIconTextGap(35);
        bIronmanQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIronmanQ2ActionPerformed(evt);
            }
        });

        bThorQ2.setBackground(new java.awt.Color(0, 0, 0));
        bThorQ2.setForeground(new java.awt.Color(255, 255, 255));
        bThorQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thoricon.jpg"))); // NOI18N
        bThorQ2.setText("THOR");
        bThorQ2.setEnabled(false);
        bThorQ2.setIconTextGap(35);
        bThorQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThorQ2ActionPerformed(evt);
            }
        });

        bCaptAmericaQ2.setBackground(new java.awt.Color(0, 0, 0));
        bCaptAmericaQ2.setForeground(new java.awt.Color(255, 255, 255));
        bCaptAmericaQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captamericaicon.jpg"))); // NOI18N
        bCaptAmericaQ2.setText("CAPTAIN AMERICA");
        bCaptAmericaQ2.setEnabled(false);
        bCaptAmericaQ2.setIconTextGap(10);
        bCaptAmericaQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptAmericaQ2ActionPerformed(evt);
            }
        });

        bHulkQ2.setBackground(new java.awt.Color(0, 0, 0));
        bHulkQ2.setForeground(new java.awt.Color(255, 255, 255));
        bHulkQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkicon.jpg"))); // NOI18N
        bHulkQ2.setText("HULK");
        bHulkQ2.setEnabled(false);
        bHulkQ2.setIconTextGap(25);
        bHulkQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHulkQ2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 255));
        jLabel7.setText("by Terrorist. He escaped by building an armored suit.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("He is a billionaire who owns the Stark Industries and was kidnapped ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avlogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCaptAmericaQ2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(bIronmanQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bThorQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIronmanQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bThorQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCaptAmericaQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("QUESTION # 2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        bIronmanQ3.setBackground(new java.awt.Color(0, 0, 0));
        bIronmanQ3.setForeground(new java.awt.Color(255, 255, 255));
        bIronmanQ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironmanicon.jpg"))); // NOI18N
        bIronmanQ3.setText(" IRON MAN");
        bIronmanQ3.setEnabled(false);
        bIronmanQ3.setIconTextGap(35);
        bIronmanQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIronmanQ3ActionPerformed(evt);
            }
        });

        bThorQ3.setBackground(new java.awt.Color(0, 0, 0));
        bThorQ3.setForeground(new java.awt.Color(255, 255, 255));
        bThorQ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thoricon.jpg"))); // NOI18N
        bThorQ3.setText("THOR");
        bThorQ3.setEnabled(false);
        bThorQ3.setIconTextGap(35);
        bThorQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThorQ3ActionPerformed(evt);
            }
        });

        bCaptAmericaQ3.setBackground(new java.awt.Color(0, 0, 0));
        bCaptAmericaQ3.setForeground(new java.awt.Color(255, 255, 255));
        bCaptAmericaQ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captamericaicon.jpg"))); // NOI18N
        bCaptAmericaQ3.setText("CAPTAIN AMERICA");
        bCaptAmericaQ3.setEnabled(false);
        bCaptAmericaQ3.setIconTextGap(10);
        bCaptAmericaQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptAmericaQ3ActionPerformed(evt);
            }
        });

        bHulkQ3.setBackground(new java.awt.Color(0, 0, 0));
        bHulkQ3.setForeground(new java.awt.Color(255, 255, 255));
        bHulkQ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkicon.jpg"))); // NOI18N
        bHulkQ3.setText("HULK");
        bHulkQ3.setEnabled(false);
        bHulkQ3.setIconTextGap(25);
        bHulkQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHulkQ3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 255));
        jLabel10.setText("Soldier Serum. He can turn to a Green Monster when he is mad.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 204, 255));
        jLabel11.setText("He is an expert on Gamma Radiation and tried to recreate the Super ");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avlogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCaptAmericaQ3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(bIronmanQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bThorQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(22, 22, 22))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIronmanQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bThorQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCaptAmericaQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("QUESTION # 3", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));

        bIronmanQ4.setBackground(new java.awt.Color(0, 0, 0));
        bIronmanQ4.setForeground(new java.awt.Color(255, 255, 255));
        bIronmanQ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironmanicon.jpg"))); // NOI18N
        bIronmanQ4.setText(" IRON MAN");
        bIronmanQ4.setEnabled(false);
        bIronmanQ4.setIconTextGap(35);
        bIronmanQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIronmanQ4ActionPerformed(evt);
            }
        });

        bThorQ4.setBackground(new java.awt.Color(0, 0, 0));
        bThorQ4.setForeground(new java.awt.Color(255, 255, 255));
        bThorQ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thoricon.jpg"))); // NOI18N
        bThorQ4.setText("THOR");
        bThorQ4.setEnabled(false);
        bThorQ4.setIconTextGap(35);
        bThorQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThorQ4ActionPerformed(evt);
            }
        });

        bCaptAmericaQ4.setBackground(new java.awt.Color(0, 0, 0));
        bCaptAmericaQ4.setForeground(new java.awt.Color(255, 255, 255));
        bCaptAmericaQ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captamericaicon.jpg"))); // NOI18N
        bCaptAmericaQ4.setText("CAPTAIN AMERICA");
        bCaptAmericaQ4.setEnabled(false);
        bCaptAmericaQ4.setIconTextGap(10);
        bCaptAmericaQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptAmericaQ4ActionPerformed(evt);
            }
        });

        bHulkQ4.setBackground(new java.awt.Color(0, 0, 0));
        bHulkQ4.setForeground(new java.awt.Color(255, 255, 255));
        bHulkQ4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkicon.jpg"))); // NOI18N
        bHulkQ4.setText("HULK");
        bHulkQ4.setEnabled(false);
        bHulkQ4.setIconTextGap(25);
        bHulkQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHulkQ4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 204, 255));
        jLabel13.setText("He uses a hammer called Mjolnir which can be lifted by worthy creatures.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 255));
        jLabel14.setText("He is also known as the God of Thunder and a Prince of Asgard.");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avlogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCaptAmericaQ4, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(bIronmanQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bThorQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIronmanQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bThorQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCaptAmericaQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHulkQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("QUESTION # 4", jPanel7);

        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SCOREBOARD");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Player Name");

        timePlayed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timePlayed.setForeground(new java.awt.Color(255, 255, 255));
        timePlayed.setText("<data>");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Date and Time Played");

        playerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        playerName.setForeground(new java.awt.Color(255, 255, 255));
        playerName.setText("<data>");

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Attempts and Scores");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Question 1");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Question 2");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Question 4");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Question 3");

        a1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("<data>");

        s1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("<data>");

        s2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("<data>");

        a2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setText("<data>");

        a3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("<data>");

        s3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setText("<data>");

        a4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("<data>");

        s4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setText("<data>");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Total Score:");

        totalScore.setForeground(new java.awt.Color(255, 255, 255));
        totalScore.setText("<data>");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Percentage:");

        percentage.setForeground(new java.awt.Color(255, 255, 255));
        percentage.setText("<data>");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23))
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(a3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(a4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(totalScore)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(percentage)
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timePlayed, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timePlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(totalScore)
                    .addComponent(jLabel37)
                    .addComponent(percentage))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.add(jLayeredPane2);
        jLayeredPane2.setBounds(110, 120, 360, 360);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avcongrats.jpg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 538, 488);

        jTabbedPane1.addTab("SCORE BOARD", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //WRONG ANSWER BUTTONS FOR QUESTION # 4
    private void bHulkQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHulkQ4ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][3]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bHulkQ4ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 4
    private void bCaptAmericaQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptAmericaQ4ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][3]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bCaptAmericaQ4ActionPerformed

    //CORRECT ANSWER BUTTON FOR QUESTION # 4   
    private void bThorQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThorQ4ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE THIRD QUESTION
        quiz_info[0][3]++;

        //SCORE FOR THE CORRECT ANSWER ON QUESTION # 4
        if(quiz_info[0][3] == 1)
        {

            quiz_info[1][3] = 25 ;

        }

        // MARK FOR SECOND ATTEMPT
        else if(quiz_info[0][3] == 2)
        {

            quiz_info[1][3] = 15 ;

        }

        else{
            quiz_info[1][3] = 0 ;
        }

         JOptionPane.showMessageDialog(null,"Congratulations you got the right answer! \nNumber of attempt in question #4 : " + quiz_info[0][3] + "  \nMark gained in question #4 : " + quiz_info[1][3]);

         a1.setText("Attempt: " + quiz_info[0][0]);
         a2.setText("Attempt: " + quiz_info[0][1]);
         a3.setText("Attempt: " + quiz_info[0][2]);
         a4.setText("Attempt: " + quiz_info[0][3]);
         
         s1.setText("Score: " + quiz_info[1][0]);
         s2.setText("Score: " + quiz_info[1][1]);
         s3.setText("Score: " + quiz_info[1][2]);
         s4.setText("Score: " + quiz_info[1][3]);
         
         Quitalig_Scores SB = new Quitalig_Scores(quiz_info);
         totalScore.setText(SB.getTotalScore(quiz_info));
         percentage.setText(SB.getPercentage(quiz_info));
         
    
         //Reset the Names
         jTextField1.setText("");
         jTextField2.setText("");
         
         //Reset the array
         for( int i = 0; i < quiz_info.length; i++ ){
            Arrays.fill( quiz_info[i],0 );
            }
        
        //Disable Quiz Buttons
            bIronmanQ1.setEnabled(false);
            bThorQ1.setEnabled(false);
            bCaptAmericaQ1.setEnabled(false);
            bHulkQ1.setEnabled(false);
            bIronmanQ2.setEnabled(false);
            bThorQ2.setEnabled(false);
            bCaptAmericaQ2.setEnabled(false);
            bHulkQ2.setEnabled(false);
            bIronmanQ3.setEnabled(false);
            bThorQ3.setEnabled(false);
            bCaptAmericaQ3.setEnabled(false);
            bHulkQ3.setEnabled(false);
            bIronmanQ4.setEnabled(false);
            bThorQ4.setEnabled(false);
            bCaptAmericaQ4.setEnabled(false);
            bHulkQ4.setEnabled(false);
            
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_bThorQ4ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 4
    private void bIronmanQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIronmanQ4ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][3]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bIronmanQ4ActionPerformed

    //CORRECT ANSWER BUTTON FOR QUESTION # 3
    private void bHulkQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHulkQ3ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE THIRD QUESTION
        quiz_info[0][2]++;

        //SCORE FOR THE CORRECT ANSWER ON QUESTION # 3
        if(quiz_info[0][2] == 1)
        {

            quiz_info[1][2] = 25 ;

        }

        // MARK FOR SECOND ATTEMPT
        else if(quiz_info[0][2] == 2)
        {

            quiz_info[1][2] = 15 ;

        }

        else{
            quiz_info[1][2] = 0 ;
        }

         JOptionPane.showMessageDialog(null,"Congratulations you got the right answer! \nNumber of attempt in question #3 : " + quiz_info[0][2] + "  \nMark gained in question #3 : " + quiz_info[1][2]);

        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_bHulkQ3ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 3
    private void bCaptAmericaQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptAmericaQ3ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][2]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bCaptAmericaQ3ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 3
    private void bThorQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThorQ3ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][2]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bThorQ3ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 3
    private void bIronmanQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIronmanQ3ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][2]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bIronmanQ3ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 2  
    private void bHulkQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHulkQ2ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][1]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bHulkQ2ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 2  
    private void bCaptAmericaQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptAmericaQ2ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][1]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bCaptAmericaQ2ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 2  
    private void bThorQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThorQ2ActionPerformed
        // TODO add your handling code here:
        quiz_info[0][1]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bThorQ2ActionPerformed

    //CORRECT ANSWER BUTTON FOR QUESTION # 2
    private void bIronmanQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIronmanQ2ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE SECOND QUESTION
        quiz_info[0][1]++;

        //SCORE FOR THE CORRECT ANSWER ON QUESTION # 2
        if(quiz_info[0][1] == 1)
        {

            quiz_info[1][1] = 25 ;

        }

        // MARK FOR SECOND ATTEMPT
        else if(quiz_info[0][1] == 2)
        {

            quiz_info[1][1] = 15 ;

        }

        else{
            quiz_info[1][1] = 0 ;
        }

        JOptionPane.showMessageDialog(null,"Congratulations you got the right answer! \nNumber of attempt in question #2 : " + quiz_info[0][1] + "  \nMark gained in question #2 : " + quiz_info[1][1]);

        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_bIronmanQ2ActionPerformed
    
    //WRONG ANSWER BUTTONS FOR QUESTION # 1
    private void bHulkQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHulkQ1ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE FIRST QUESTION
        quiz_info[0][0]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bHulkQ1ActionPerformed

    //CORRECT ANSWER BUTTON FOR QUESTION # 1
    private void bCaptAmericaQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptAmericaQ1ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE FIRST QUESTION
        quiz_info[0][0]++;

        //SCORE FOR THE CORRECT ANSWER ON QUESTION # 1

        if(quiz_info[0][0] == 1)
        {

            quiz_info[1][0] = 25 ;

        }

        // MARK FOR SECOND ATTEMPT
        else if(quiz_info[0][0] == 2)
        {

            quiz_info[1][0] = 15 ;

        }

        else{
            quiz_info[1][0] = 0 ;
        }

        JOptionPane.showMessageDialog(null,"Congratulations you got the right answer! \nNumber of attempt in question #1 : " + quiz_info[0][0] + "  \nMark gained in question #1 : " + quiz_info[1][0]);

        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_bCaptAmericaQ1ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 1
    private void bThorQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThorQ1ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE FIRST QUESTION
        quiz_info[0][0]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bThorQ1ActionPerformed

    //WRONG ANSWER BUTTONS FOR QUESTION # 1
    private void bIronmanQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIronmanQ1ActionPerformed
        // TODO add your handling code here:

        //ATTEMPT FOR THE FIRST QUESTION
        quiz_info[0][0]++;
        JOptionPane.showMessageDialog(null,"Your answer is incorrect!");
    }//GEN-LAST:event_bIronmanQ1ActionPerformed

    
    
   // EXIT BUTTON ON TAB 1
    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    //LOGIN AND PLAY BUTTON
    private void bLoginAndPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginAndPlayActionPerformed
        // TODO add your handling code here:

        // Condition if full name is not entered
        if(jTextField1.getText().equals("")  || jTextField2.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please enter your full name!");
        }
        else
        {
            fname = jTextField1.getText();
            lname = jTextField2.getText();
            jTabbedPane1.setSelectedIndex(1);
            timePlayed.setText(dateFormat.format(date));
            playerName.setText(fname + " " + lname);

            //Enable Quiz Buttons
            bIronmanQ1.setEnabled(true);
            bThorQ1.setEnabled(true);
            bCaptAmericaQ1.setEnabled(true);
            bHulkQ1.setEnabled(true);
            bIronmanQ2.setEnabled(true);
            bThorQ2.setEnabled(true);
            bCaptAmericaQ2.setEnabled(true);
            bHulkQ2.setEnabled(true);
            bIronmanQ3.setEnabled(true);
            bThorQ3.setEnabled(true);
            bCaptAmericaQ3.setEnabled(true);
            bHulkQ3.setEnabled(true);
            bIronmanQ4.setEnabled(true);
            bThorQ4.setEnabled(true);
            bCaptAmericaQ4.setEnabled(true);
            bHulkQ4.setEnabled(true);

        }
    }//GEN-LAST:event_bLoginAndPlayActionPerformed

    
    
    
    
    
  
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quitalig_HeroQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quitalig_HeroQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quitalig_HeroQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quitalig_HeroQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quitalig_HeroQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JButton bCaptAmericaQ1;
    private javax.swing.JButton bCaptAmericaQ2;
    private javax.swing.JButton bCaptAmericaQ3;
    private javax.swing.JButton bCaptAmericaQ4;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHulkQ1;
    private javax.swing.JButton bHulkQ2;
    private javax.swing.JButton bHulkQ3;
    private javax.swing.JButton bHulkQ4;
    private javax.swing.JButton bIronmanQ1;
    private javax.swing.JButton bIronmanQ2;
    private javax.swing.JButton bIronmanQ3;
    private javax.swing.JButton bIronmanQ4;
    private javax.swing.JButton bLoginAndPlay;
    private javax.swing.JButton bThorQ1;
    private javax.swing.JButton bThorQ2;
    private javax.swing.JButton bThorQ3;
    private javax.swing.JButton bThorQ4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel timePlayed;
    private javax.swing.JLabel totalScore;
    // End of variables declaration//GEN-END:variables
}
